version: '3.5'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3306:3306"
    volumes:
        - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      devnet:
        ipv4_address: 172.19.0.10

  adminer:
    image: adminer
    restart: always
    ports:
    - "13306:8080"
    networks:
      devnet:
        ipv4_address: 172.19.0.11

networks:
  devnet:
    external:
      name: devnet
